class CampaignMailer < ApplicationMailer
  ##
  # Delivers a campaign email to a single lead.
  #
  # @param to [String] recipient email address
  # @param recipient_name [String] recipient name (optional, used in templates)
  # @param email_content [String] HTML/markdown content generated by agents
  # @param campaign_title [String] campaign title used for subject line context
  def send_email(to:, recipient_name:, email_content:, campaign_title:, from_email: nil)
    @recipient_name = recipient_name
    @campaign_title = campaign_title
    @email_content = email_content

    mail(
      to: to,
      from: from_email.presence || ApplicationMailer.default[:from],
      subject: build_subject(campaign_title, recipient_name)
    )
  end

  private

  def build_subject(campaign_title, recipient_name)
    base = campaign_title.presence || "Campaign Outreach"
    if recipient_name.present? && recipient_name.strip.present?
      "#{base} – Outreach for #{recipient_name}"
    else
      "#{base} – Outreach Update"
    end
  end
end
