source "https://rubygems.org"

ruby '3.3.8'

gem "rails", "~> 7.0"
gem "puma", "~> 6.0"
gem 'httparty'        # for Tavily/OpenAI API calls
gem 'dotenv-rails'    # to load environment variables
gem "bootsnap", require: false
gem "rack-cors"

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'webmock', '~> 3.18'
  gem 'simplecov', require: false
end


