require "httparty"
require "json"

=begin
DESIGN AGENT

OVERVIEW:
The DesignAgent uses Google's Gemini AI to apply formatting (bold, italic) to email content
generated by the WriterAgent. It enhances the email with visual emphasis to improve readability
and engagement.

HOW IT WORKS:
1. Receives email content from WriterAgent
2. Analyzes the content to identify key phrases, important points, and emphasis opportunities
3. Applies bold formatting to key terms, company names, and important concepts
4. Applies italic formatting to quotes, emphasis, and subtle highlights
5. Returns formatted email with HTML or markdown formatting

INPUT:
writer_output:
  {
    email: "Subject: ...\n\nHi John,\n...",
    company: "Microsoft",
    recipient: "John Doe"
  }

OUTPUT:
{
  email: "Subject: ...\n\nHi **John**,\n...",
  formatted_email: "<strong>...</strong> or **...**",
  company: "Microsoft",
  recipient: "John Doe"
}

KEY FEATURES:
- Applies bold formatting to important terms, company names, and key concepts
- Applies italic formatting for emphasis and quotes
- Maintains email structure and readability
- Preserves original content intent
=end

module Agents
  class DesignAgent
    include HTTParty
    base_uri "https://generativelanguage.googleapis.com/v1beta"

    def initialize(api_key:, model: "gemini-2.5-flash")
      @api_key = api_key
      @model = model
      raise ArgumentError, "Gemini API key is required" if @api_key.blank?
    end

    def run(writer_output, config: nil)
      email_content = writer_output[:email] || writer_output["email"] || ""
      company = writer_output[:company] || writer_output["company"]
      recipient = writer_output[:recipient] || writer_output["recipient"]

      # Extract settings from config (handle both camelCase and snake_case)
      settings = config&.dig(:settings) || config&.dig("settings") || {}
      format = settings[:format] || settings["format"] || "formatted"

      # If email is empty, return original output with format
      if email_content.blank?
        return {
          email: email_content,
          formatted_email: email_content,
          format: format,
          company: company,
          recipient: recipient
        }
      end
      # Default to true unless explicitly set to false (check all key variations)
      allow_bold = !(settings[:allow_bold] == false || settings["allow_bold"] == false || settings[:allowBold] == false || settings["allowBold"] == false)
      allow_italic = !(settings[:allow_italic] == false || settings["allow_italic"] == false || settings[:allowItalic] == false || settings["allowItalic"] == false)
      allow_bullets = !(settings[:allow_bullets] == false || settings["allow_bullets"] == false || settings[:allowBullets] == false || settings["allowBullets"] == false)
      cta_style = settings[:cta_style] || settings["cta_style"] || settings[:ctaStyle] || settings["ctaStyle"] || "link"
      font_family = settings[:font_family] || settings["font_family"] || settings[:fontFamily] || settings["fontFamily"]

      prompt = build_prompt(email_content, company, recipient, format: format, allow_bold: allow_bold, allow_italic: allow_italic, allow_bullets: allow_bullets, cta_style: cta_style, font_family: font_family)

      # Build full prompt with system instructions
      full_prompt = "You are an expert email designer who enhances email content with strategic formatting to improve readability and engagement. Apply bold and italic formatting thoughtfully.\n\n#{prompt}"

      response = self.class.post(
        "/models/#{@model}:generateContent?key=#{@api_key}",
        headers: {
          "Content-Type" => "application/json"
        },
        body: {
          contents: [
            {
              parts: [
                {
                  text: full_prompt
                }
              ]
            }
          ],
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 8192
          }
        }.to_json
      )

      parsed_response = JSON.parse(response.body)

      # Extract formatted email from Gemini response
      candidate = parsed_response.dig("candidates", 0)

      if candidate && candidate["content"] && candidate["content"]["parts"]
        formatted_email = candidate["content"]["parts"][0]["text"] || email_content
      else
        formatted_email = email_content
      end

      {
        email: formatted_email,
        formatted_email: formatted_email,
        format: format,
        company: company,
        recipient: recipient,
        original_email: email_content
      }
    rescue => e
      {
        email: email_content,
        formatted_email: email_content,
        format: format,
        company: company,
        recipient: recipient,
        original_email: email_content,
        error: "DesignAgent LLM error: #{e.class}: #{e.message}"
      }
    end

    private

    def build_prompt(email_content, company, recipient, format: "formatted", allow_bold: true, allow_italic: true, allow_bullets: true, cta_style: "link", font_family: nil)
      # If format is plain_text, return the content as-is without formatting instructions
      if format == "plain_text"
        prompt = "Return the following email content as plain text without any formatting:\n"
        prompt += "- Do not add any markdown, HTML, or other formatting\n"
        prompt += "- Keep the exact same structure and content\n\n"
      else
        prompt = "Apply formatting to the following email content using markdown syntax:\n"

        # Conditionally include formatting instructions based on settings
        if allow_bold
          prompt += "- Use **bold** for: company names, key terms, important concepts, product names, and call-to-action phrases\n"
        end

        if allow_italic
          prompt += "- Use *italic* for: emphasis, quotes, subtle highlights, and secondary important information\n"
        end

        if allow_bullets
          prompt += "- Use bullet points (- or *) for lists when appropriate\n"
        end

        prompt += "- Use ~~strikethrough~~ for: crossed-out text, discounts, or old prices\n"
        prompt += "- Use `code` for: technical terms, product codes, or inline code references\n"

        # Apply CTA style guidance
        if cta_style == "button"
          prompt += "- Format call-to-action phrases as button-style: **[CTA text]** or use emphasis to make them stand out\n"
        else
          prompt += "- Use [link text](url) for: clickable links (only if URLs are provided)\n"
        end

        prompt += "- Use > quote for: important quotes or testimonials\n"
        prompt += "- Keep the Subject line unchanged (do not format it)\n"
        prompt += "- Maintain all line breaks and structure\n"
        prompt += "- Do not change the content, only add formatting\n"
        prompt += "- Be selective - don't over-format. Only format truly important elements\n"

        # Apply font family guidance if relevant (mainly for documentation, not directly applicable to markdown)
        if font_family
          prompt += "- Consider typography: #{font_family == 'serif' ? 'Use serif-style emphasis for formal content' : 'Use system sans-serif style for modern, clean appearance'}\n"
        end

        prompt += "\n"
      end

      if company
        prompt += "Company: #{company}\n"
      end

      if recipient
        prompt += "Recipient: #{recipient}\n"
      end

      prompt += "\nEmail content to format:\n"
      prompt += "---\n"
      prompt += email_content
      prompt += "\n---\n\n"

      prompt += "Return the formatted email with markdown formatting applied. Keep the exact same structure and content, only add formatting (bold, italic, strikethrough, code, links, quotes) where appropriate."

      prompt
    end
  end
end
