require "httparty"
require "json"

=begin
DESIGN AGENT

OVERVIEW:
The DesignAgent uses Google's Gemini AI to apply formatting (bold, italic) to email content
generated by the WriterAgent. It enhances the email with visual emphasis to improve readability
and engagement.

HOW IT WORKS:
1. Receives email content from WriterAgent
2. Analyzes the content to identify key phrases, important points, and emphasis opportunities
3. Applies bold formatting to key terms, company names, and important concepts
4. Applies italic formatting to quotes, emphasis, and subtle highlights
5. Returns formatted email with HTML or markdown formatting

INPUT:
writer_output:
  {
    email: "Subject: ...\n\nHi John,\n...",
    company: "Microsoft",
    recipient: "John Doe"
  }

OUTPUT:
{
  email: "Subject: ...\n\nHi **John**,\n...",
  formatted_email: "<strong>...</strong> or **...**",
  company: "Microsoft",
  recipient: "John Doe"
}

KEY FEATURES:
- Applies bold formatting to important terms, company names, and key concepts
- Applies italic formatting for emphasis and quotes
- Maintains email structure and readability
- Preserves original content intent
=end

module Agents
  class DesignAgent
    include HTTParty
    base_uri "https://generativelanguage.googleapis.com/v1beta"

    def initialize(api_key:, model: "gemini-2.5-flash")
      @api_key = api_key
      @model = model
      raise ArgumentError, "Gemini API key is required" if @api_key.blank?
    end

    def run(writer_output)
      email_content = writer_output[:email] || writer_output["email"] || ""
      company = writer_output[:company] || writer_output["company"]
      recipient = writer_output[:recipient] || writer_output["recipient"]

      # If email is empty, return original output
      if email_content.blank?
        return {
          email: email_content,
          formatted_email: email_content,
          company: company,
          recipient: recipient
        }
      end

      prompt = build_prompt(email_content, company, recipient)

      # Build full prompt with system instructions
      full_prompt = "You are an expert email designer who enhances email content with strategic formatting to improve readability and engagement. Apply bold and italic formatting thoughtfully.\n\n#{prompt}"

      response = self.class.post(
        "/models/#{@model}:generateContent?key=#{@api_key}",
        headers: {
          "Content-Type" => "application/json"
        },
        body: {
          contents: [
            {
              parts: [
                {
                  text: full_prompt
                }
              ]
            }
          ],
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 8192
          }
        }.to_json
      )

      parsed_response = JSON.parse(response.body)

      # Extract formatted email from Gemini response
      candidate = parsed_response.dig("candidates", 0)

      if candidate && candidate["content"] && candidate["content"]["parts"]
        formatted_email = candidate["content"]["parts"][0]["text"] || email_content
      else
        formatted_email = email_content
      end

      {
        email: formatted_email,
        formatted_email: formatted_email,
        company: company,
        recipient: recipient,
        original_email: email_content
      }
    rescue => e
      {
        email: email_content,
        formatted_email: email_content,
        company: company,
        recipient: recipient,
        original_email: email_content,
        error: e.message
      }
    end

    private

    def build_prompt(email_content, company, recipient)
      prompt = "Apply formatting to the following email content using markdown syntax:\n"
      prompt += "- Use **bold** for: company names, key terms, important concepts, product names, and call-to-action phrases\n"
      prompt += "- Use *italic* for: emphasis, quotes, subtle highlights, and secondary important information\n"
      prompt += "- Use ~~strikethrough~~ for: crossed-out text, discounts, or old prices\n"
      prompt += "- Use `code` for: technical terms, product codes, or inline code references\n"
      prompt += "- Use [link text](url) for: clickable links (only if URLs are provided)\n"
      prompt += "- Use > quote for: important quotes or testimonials\n"
      prompt += "- Keep the Subject line unchanged (do not format it)\n"
      prompt += "- Maintain all line breaks and structure\n"
      prompt += "- Do not change the content, only add formatting\n"
      prompt += "- Be selective - don't over-format. Only format truly important elements\n\n"

      if company
        prompt += "Company: #{company}\n"
      end

      if recipient
        prompt += "Recipient: #{recipient}\n"
      end

      prompt += "\nEmail content to format:\n"
      prompt += "---\n"
      prompt += email_content
      prompt += "\n---\n\n"

      prompt += "Return the formatted email with markdown formatting applied. Keep the exact same structure and content, only add formatting (bold, italic, strikethrough, code, links, quotes) where appropriate."

      prompt
    end
  end
end
