require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  if defined?(ActiveStorage::Engine)
    config.active_storage.service = :local
  end

  # Raise delivery errors in development if SMTP is configured
  config.action_mailer.raise_delivery_errors = ENV["SMTP_ADDRESS"].present?

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Configure email delivery method
  # Option 1: Use SMTP (if SMTP_ADDRESS is set) - will actually send emails
  # Option 2: Use file delivery (default) - saves emails to tmp/mail for testing
  # Option 3: Use test delivery - accumulates emails in ActionMailer::Base.deliveries
  if ENV["SMTP_ADDRESS"].present?
    # Use SMTP if configured (for testing real email sending in development)
    config.action_mailer.delivery_method = :smtp
    config.action_mailer.smtp_settings = {
      address: ENV.fetch("SMTP_ADDRESS"),
      port: ENV.fetch("SMTP_PORT", "587").to_i,
      domain: ENV.fetch("SMTP_DOMAIN", "localhost"),
      user_name: ENV.fetch("SMTP_USER_NAME", ""),
      password: ENV.fetch("SMTP_PASSWORD", ""),
      authentication: ENV.fetch("SMTP_AUTHENTICATION", "plain").to_sym,
      enable_starttls_auto: ENV.fetch("SMTP_ENABLE_STARTTLS", "true") == "true",
      # Fix SSL certificate verification issue in development
      openssl_verify_mode: "none"  # Only for development - disable SSL verification
    }
  elsif ENV["MAIL_DELIVERY_METHOD"] == "test"
    # Use test delivery (emails stored in ActionMailer::Base.deliveries array)
    config.action_mailer.delivery_method = :test
  else
    # Default: Use file delivery (saves emails to tmp/mail directory)
    config.action_mailer.delivery_method = :file
    config.action_mailer.file_settings = { location: Rails.root.join("tmp", "mail") }
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Active Record configs are disabled while AR is skipped in Phase 2.
  if defined?(ActiveRecord)
    # Raise an error on page load if there are pending migrations.
    config.active_record.migration_error = :page_load
    # Highlight code that triggered database queries in logs.
    config.active_record.verbose_query_logs = true
    # Append comments with runtime information tags to SQL queries in logs.
    config.active_record.query_log_tags_enabled = true
  end

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
